/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface2.h"


void
autorizar_usuarios_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	nodo_usuario  objUsuario;
	nodo_usuario  *objUsuarioResultado;
	char * codigo;

#ifndef	DEBUG
	clnt = clnt_create (host, autorizar_usuarios, autorizar_usuarios_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int opcion;
	do
	{
		printf("\n================ Menu ==================");
		printf("\n 1. Registrar usuario ");
		printf("\n 2. Consultar usuario ");
		printf("\n 3. Salir ");
		printf("\n=======================================");
		printf("\n Digite opcion: ");
		scanf("%d",&opcion);
		switch(opcion)
		{    
			case 1:
				printf("\n Digite el codigo: ");				
				scanf("%s",objUsuario.codigo);
				printf("Digite el nombre del usuario: ");
				scanf("%s",objUsuario.nombres);
				printf("Digite el apellido del usuario: ");
				scanf("%s",objUsuario.apellidos);
				printf("Digite el rol del usuario: ");
				scanf("%s",objUsuario.rol);
	
				result_1=registrarusuariosistema_1(&objUsuario,clnt);
				if(result_1 == (bool_t *)NULL)
				{
				  clnt_perror(clnt,"call failed");
				}
				else if(*result_1==TRUE)
				{
				  printf("Usuario registrado exitosamente\n");
				}
				else
				{
				  printf("\n Usuario no registrado");
				}
				break;

			case 2:
				printf("\n Consultar usuario");
				codigo=(char*)malloc(sizeof(char)*20);
				printf("\nDigite el codigo del usuario:");
				scanf("%s",codigo);
				objUsuarioResultado=consultarusuario_1(&codigo,clnt);
				if (objUsuarioResultado == (nodo_usuario *) NULL) 
				{	
				  clnt_perror(clnt, "Call failed");
				}else if (strcmp((*objUsuarioResultado).codigo, "-1")==0){
					printf("\nNo existe el Usuario");
				}
				else
				{
				  printf("\nCodigo: %s",(*objUsuarioResultado).codigo);
				  printf("\nNombres: %s",(*objUsuarioResultado).nombres);
				  printf("\nApellidos: %s",(*objUsuarioResultado).apellidos);
				  printf("\nRol: %s",(*objUsuarioResultado).rol);

				}
				break;

			case 3:
				printf("\nSaliendo ...");
				break;
		
			default:
				printf("Opcion invalida\n");
				break;				
		}
	}while(opcion < 3);
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	autorizar_usuarios_1 (host);
exit (0);
}
