/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface2.h"

nodo_usuario vectorUsuarios[5];
int posUsuario = 0;

bool_t *
registrarusuariosistema_1_svc(nodo_usuario *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	printf("\n\n Registrando usuario. ");
	if(posUsuario < 4){
		vectorUsuarios[posUsuario] = *argp;
		posUsuario++;
		printf("\n Usuario registrado. ");
		result = TRUE;
	}
	else
	{
		printf("\n Cantidad maxima de usuarios alcanzada. ");
		result = FALSE;
	}
	return &result;
}

nodo_usuario *
consultarusuario_1_svc(char **codigo, struct svc_req *rqstp)
{
	static nodo_usuario  result;
	printf("\n\n Consultando usuario. ");
	int i, bandera;
	bandera = 0;
	for(i = 0; i < 5; i++){
		if (strcmp(*codigo, vectorUsuarios[i].codigo) == 0)
		{
			result = vectorUsuarios[i];
			bandera = 1;
			break;
		}
	}
	if(bandera == 0){
		printf("\n El usuario con codigo %s no se encuentra registrado.\n", *codigo);
		strcpy(result.codigo,"-1");
	}
	return &result;
}
